services:
  mockserver:
    restart: always
    image: mockoon/cli:2.4.0
    ports:
      - 3000:3000
    command: "-d https://raw.githubusercontent.com/digitalfemsa/openapi/main/mocks/femsa.json -p 3000 --log-transaction"
    healthcheck:
      test: "wget -qO - http://mockserver:3000/ping"
      interval: 5s
      timeout: 10s
      retries: 20
  service:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     BASE_PATH: "http://mockserver:3000"
   depends_on:
    mockserver:
      condition: service_healthy
   volumes:
    - ./coverage:/usr/src/app/coverage
